name: Build docker image on push

on:
  pull_request:

  push:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      env:
        EXTENSION_VERSION: ${{ github.head_ref || github.ref_name }}
        GITHUB_ORG: ${{ github.event.pull_request.head.repo.owner.login || github.repository_owner }}
      run: |
        echo "FROM python:3.13-slim-bullseye" | cat - Dockerfile | echo 'CMD ["./start_servers.sh"]' | docker build \
            --build-arg EXTENSION_VERSION=$EXTENSION_VERSION \
            --build-arg GITHUB_ORG=$GITHUB_ORG \
            -
